### ISSUE TITLE
[Tracking Issue]: Add responsive design to 100eyes

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#1539]
```
As an editor 
I want to use 100eyes on my phone to keep track of my dialogue and my community's messages. Therefore I use 100eyes on my little phone screen when I am on the road. Unfortunately it looks very ugly right now because it is not responsive. Please change and add responsiveness.
```

- [ ] Navbar responsiveness https://github.com/tactilenews/100eyes/issues/1559
- [ ] RequestForm responsiveness https://github.com/tactilenews/100eyes/issues/1560
- [ ] Request show page responsiveness https://github.com/tactilenews/100eyes/issues/1561
- [ ] Request index page responsiveness https://github.com/tactilenews/100eyes/issues/1562
- [ ] Dashboard responsiveness https://github.com/tactilenews/100eyes/issues/1563
- [ ] Contributors show page responsiveness https://github.com/tactilenews/100eyes/issues/1564
- [ ] Contributors index page responsiveness https://github.com/tactilenews/100eyes/issues/1565

**Comment by mattwr18** [comment]
@FrauCsu, just to put it somewhere in writing. I think that this is a huge task and would be better to have individual issues prioritized by page. Then, we can divide the work, keep the PRs relatively small, and feel a sense that we are moving forward.

Maybe, this could be a tracking issue with a checklist and link to the individual issues?

**Comment by mattwr18** [comment]
@FrauCsu @drjakob I've created issues for individual parts/pages and put them in rough prioritization as I see it.
Please review and update the list to move up/down the issues if you think some are more/less important than others.

I will move this tracking issue into future quarter. Maybe, we could get to one or two of the issues this quarter depending on peoples' availability.
