### ISSUE TITLE
[Tracking issue] 360dialog WhatsApp

### ISSUE THREAD

**Issue by mattwr18** [tactilenews/100eyes#2026]
### Migrate to Cloud API (required as new registrations not possible after May 2024)
- [x] Enable Partner Account to use Cloud API - allows selecting region where data is stored.
- [x] Generate new API keys for existing numbers
- [x] Follow the Cloud migration assistant - may take between 5 to 60 minutes
- [x] Update the base_uri in the application
- [x] Re-set the webhook url as creating a new api key invalidates the webhook url. This is done in the CreateApiKeyJob
- [ ] ~Update the create template enpoint `/v1/config/templates`~
- [x] Add `messaging_product` to  payloads
- [x] Update template payload to remove namespace

### other improvements
- [x] Adapt the webhook url for multi-tenancy (required)
- [x] ~Add the update business profile api (would be good to have, otherwise client would need to add all this)~
- [X] Save the message id to external id (improvement)
- [x] Handle statuses (improvement)
- [X] Add a CreateTemplateJob that allows for creating single templates on demand, for example when the welcome message is changed.

### Related issues

- [x] [ [fix] Update 360dialog for Cloud API #2028 ](https://github.com/tactilenews/100eyes/issues/2028)
- [x]  [[fix] Adapt the webhook url for multi-tenancy #2029 ](https://github.com/tactilenews/100eyes/issues/2029)
- [x] [[improvement] 360dialog Add Business Profile API #2030 ](https://github.com/tactilenews/100eyes/issues/2030)
- [x] [[improvement] 360dialog extend request to receive message feature #2031](https://github.com/tactilenews/100eyes/issues/2031)
- [x]  [[improvement] 360dialog Handle statuses #2032](https://github.com/tactilenews/100eyes/issues/2032) 
- [x]  [[improvement] 360dialog Add CreateTemplateJob #2033](https://github.com/tactilenews/100eyes/issues/2033)

**Comment by mattwr18** [comment]
I think we implemented everything in this issue, so I'm closing it.
